JqueryCrud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include("books.urls", namespace="books")),
]

books/urls.py
from django.urls import path
from . import views

app_name = "books"
urlpatterns = [
    # path('', include("books.urls")),
    path("",views.book_list, name="book_list"),
    path("create/", views.book_create, name="book_create"),
    path("<int:id>/update/", views.book_update, name="book_update"),
    path("<int:id>/delete/", views.book_delete, name="book_delete"),

]

books/models.py
from django.db import models

# Create your models here.
HARDCOVER = 1
PAPERBACK = 2
EBOOK = 3
BOOK_TYPES = (
    (HARDCOVER, 'Hardcover'),
    (PAPERBACK, 'Paperback'),
    (EBOOK, 'E-book'),
)
class Book(models.Model):
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

books/forms.py
from django.utils import timezone
from django.forms import SelectDateWidget
from django import forms
from .models import Book


# def past_years(ago):
#     this_year = timezone.now().year
#     return list(range(this_year-ago-1,this_year))

# class DateInput(forms.DateInput):
#     input_type="date"

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = "__all__"
        widgets = {
            # "publication_date": DateInput(),
            "publication_date": forms.DateInput(attrs={
                'type':'date',
                'required':True
            })
        }

books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import Book
from .forms import BookForm

# Create your views here.
def save_book_form(request, form, template_name):
    data = dict()
    if request.method == "POST":
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            books = Book.objects.all()
            data['html_book_list'] = render_to_string("books/includes/partial_book_list.html", {'book_list':books})
        else:
            data['form_is_valid'] = False
    context = {'form':form}
    data['html_form'] = render_to_string(
        template_name,
        context,
        request=request
    )
    return JsonResponse(data)

def book_list(request):
    books = Book.objects.all()
    return render(request, "books/book_list.html", {'book_list':books})
    
def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()
    return save_book_form(request, form, "books/includes/partial_book_create.html")

def book_update(request,id):
    book = get_object_or_404(Book, id=id)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)
    return save_book_form(request, form, "books/includes/partial_book_update.html")

def book_delete(request, id):
    book = get_object_or_404(Book, id=id)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        books = Book.objects.all()
        data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
            'book_list': books
        })
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('books/includes/partial_book_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)

books/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <title>Bookstore - Simple is Better Than Complex</title>
  </head>
  <body>
    {% comment %} {% include 'includes/header.html' %} {% endcomment %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock %}
  </body>
</html>

books/templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <h1 class="page-header">Books</h1>
    <p>
        <button type="button" 
        class="btn btn-primary js-create-book"
        data-url="{% url 'books:book_create' %}">
            <i class="far fa-plus-square"> New Book</i>
        </button>
    </p>
    
  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Author</th>
        <th>Type</th>
        <th>Publication date</th>
        <th>Pages</th>
        <th>Price</th>
        <th>Update</th>
      </tr>
    </thead>
    <tbody>
      {% include  "books/includes/partial_book_list.html" %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
        <div class="modal-content">
        
        </div>
    </div>
  </div>
{% endblock %}
{% block javascript %}
<script src="{% static 'books/js/books.js' %}"></script>
{% endblock%}

books/templates/books/includes/partial_book_create.html
{% comment %} {% load widget_tweaks %} {% endcomment %}

<form method="post" action="{% url 'books:book_create'%}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Create a new book</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include "books/includes/partial_book_form.html" %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

books/templates/books/includes/partial_book_delete.html
<form method="post" action="{% url 'books:book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm book deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete book</button>
  </div>
</form>

books/templates/books/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
        <p class="help-block">{{ error }}</p>
    {% endfor %}
    </div>
{% endfor %}

books/templates/books/includes/partial_book_list.html
{% for book in book_list %}
<tr>
    <td>{{ book.id }}</td>
    <td>{{ book.title }}</td>
    <td>{{ book.author }}</td>
    <td>{{ book.get_book_type_display }}</td>
    <td>{{ book.publication_date }}</td>
    <td>{{ book.pages }}</td>
    <td>{{ book.price }}</td>
    <td>
      <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="{% url 'books:book_update' book.id %}">
        <i class="fas fa-pencil-alt"></i> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="{% url 'books:book_delete' book.id %}">
        <i class="far fa-trash-alt"></i> Delete
      </button>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="8" class="text-center bg-warning">No book</td>
</tr>
{% endfor %}  

books/templates/books/includes/partial_book_update.html
<form method="post" action="{% url 'books:book_update' form.instance.id %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Edit Book</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include "books/includes/partial_book_form.html" %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update</button>
  </div>
</form>